version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: freenance
      POSTGRES_DB: freenance
    networks:
      - freenance
networks:
  freenance:
